edition = "2018"
fn_single_line = true
format_code_in_doc_comments = true
inline_attribute_width = 80
match_block_trailing_comma = true
max_width = 100
imports_granularity = "Module"
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
report_fixme = "Always"
report_todo = "Always"
use_small_heuristics = "Default"
wrap_comments = true
